### ISSUE TITLE
Chaining operators documentation typo?

### ISSUE THREAD

**Issue by ephetic** [sergeyshpadyrev/una#13]
The sections for the both the left and right chaining operator say they are by last parameter, making it hard to see what the difference in semantics is meant to be.

```
Right chainging arrow |> is chaining by last parameter.
```

```
Left chainging arrow <| is chaining by last parameter.
```

**Comment by sergeyshpadyrev** [comment]
Yes, you right. I fixed the typo and added more explanations about these operators.
